<!--Método para invocar la sesion de un usuario antes de manipularlo-->
<?php
session_start(); 
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Usuario</title>
    <link rel="stylesheet" type="text/css" href="../css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="../css/font-awesome.css">
	<style>
	.button {
		background-color: #e7e7e7e7; /* Green */
		border: none;
		color: black;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 16px;
		margin: 4px 2px;
		cursor: pointer;
	}
	.button1 {padding: 10px 24px;}
	</style>
  </head>
     
  <body onload="buscarusuario()">  
      <div id="header-login">
         <?php 
         include ('../header/header_superadministrador.php');
         ?>
      </div>	  
	  
	  <!--Formulario de usuario(Jefe de departamento y jefe encargado tesjo)-->
            <div class="form-group col-xs-12"> 	
          		<?php
                echo ' <div class="container">';
			    echo '  <h2>Menú de Ayuda (General)</h2>';
				echo '  <p><strong>Nota:</strong> Da un <strong>clic</strong> sobre la consulta que deseas realizar (Automáticamente se desplará un formulario con la información requerida)</p>';
				echo '  <div class="panel-group" id="accordion">';
				
				echo '<div class="panel panel-primary">';
                echo '    <div class="panel panel-primary">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse8"><div class="panel-heading">Menú de Ayuda <i class="fa fa-question-circle" aria-hidden="true"></i> (Alumnos) <i class="fa fa-user fa-2x" aria-hidden="true"></i>       <center><i class="fa fa-angle-down" aria-hidden="true"> Desglosa aquí</i></center></div></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse8" class="panel-collapse collapse">';
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse9"><b>Agregar Alumno</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse9" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para agregar un <b> Alumno </b>:<br><br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Alumnos</button><br><br>';
				echo '        <b>Paso 2.-</b> Ir al botón   <button type="button" class="btn btn-default"><font color="green"><i class="fa fa-plus-circle fa-1x" aria-hidden="true"> Agregar Alumno</i></font></button><br><br>';
				echo '        <b>Paso 3.-</b> Llenar el formulario </b><b>NUEVO ALUMNO</b><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Guardar</button> (Si es que se desea guardar) ó bien  en el botón   <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desean guardar los datos).<br><br>';
				echo '        Si los datos ingresados fueron correctos, <b>aparecerá el siguiente mensaje:</b><br><br>';
	            echo '        <div class="alert alert-success alert-dismissible fade in">';
                echo '            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '            <center> Alumno guardado correctamente</center>';
                echo '        </div>				';
                echo '       <font color="gray">Una vez enviado esté mensaje, se podrán visualizar los datos del alumno agregado en el sistema web.</font></div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse10"><b>Búsqueda de Alumnos</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse10" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para la realización de una búsqueda<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Alumnos</button><br><br>';
				echo '        <b>Paso 2.-</b> Posicionar el mouse en la caja de búsqueda <input type="text" placeholder="BUSCAR..."><br><br>';
				echo '        <b>Paso 3.-</b> Posicionar el mouse a mano derecha y seleccionar el tipo de búsqueda'; 
                echo '      <select>';
				echo '			  <option value="usuario">No. Control</option>';
				echo '			  <option value="nombre>Nombre</option>';
				echo '			  <option value="ap">Apellido Paterno</option>';
				echo '			  <option value="am">Apellido Materno</option>';
				echo '			  <option value="puesto">Status</option>';
				echo '			</select>
				(No. Control, Nombre, Apellido Paterno, Apellido Materno, Status)<br><br>';
				echo '        <b>Paso 4.-</b> Introducir el dato a buscar <br><br>Si el dato que se introdujo en la caja de búsqueda es correcto regresara el dato buscado.<br><br>Si el dato que se introdujo en la caja de búsqueda es incorrecto, se mostrará un mensaje de error (De acuerdo al dato de búsqueda).</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse11"><b>Importar una lista de Alumnos</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse11" class="panel-collapse collapse">';
                echo '        <div class="panel-body">Si usted tiene una larga lista de Alumnos y no los quiere llenar manualmente en el sistema (le tenemos una solución, Importar una lista de Alumnos en excel)<br><br>';
				echo '        Pasos para importar una <b> Lista de Alumnos </b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Alumnos</button><br><br>';	
			    echo '        <b>Paso 2.-</b> Dar clic en el botón <div class="well"><center><font color="blue">¿Deseas importar una lista de Alumnos?, Desglosa aquí aquí</font></center></div>';
	            echo '        <b><font color="grey">Una vez que haya dado clic se desplazara un ventana informativa</font></b>, en donde se podrá <b><font color="green"><i class="fa fa-download" aria-hidden="true"> </i></font><font color="blue"> Descargar plantilla </font></b><b>(alumno.csv)</b><br><br></font>';
			    echo '        <b>Paso 3.-</b> Abrir la plantilla <b>alumno.csv</b> y llenarla con los datos requeridos en la parte superior del archivo (En la parte izquierda viene un ejemplo)<br><br></b>';
			    echo '        Una vez que todos los capos hayan sido llenados se le da guardar al archivo <b>(alumno.csv)</b> y nos regresamos al formulario del usuario <br><br></b>';
			    echo '        <b>Paso 4.-</b> Seleccionamos el botón <b>Seleccionar archivo</b>, El cual desplegará una ventana de búsqueda, seleccionamos el archivo <b>(alumno.csv)</b><br><br>';
				echo '        <b>Paso 5.-</b> Damos clic en abrir (Una vez hecho estó se cargara el nombre del archivo )<br><br>';
				echo '        <b>Paso 6.-</b> Dar clic en el botón <button type="button"><font color="green">Cargar</font></button><br><br>';
				echo '        Si los datos ingresados fueron correctos, <b>aparecerá el siguiente mensaje:</b> <br><br>';
				echo '       <div class="alert alert-success alert-dismissible fade in">';
                echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '             <center>Archivo importado correctamente</center>';
                echo '       </div>';
				echo '  <font color="gray">Una vez enviado esté mensaje, se podrán visualizar los datos del usuario agregado en el sistema web.</font><br><br>';
			    echo '       Si el archivo importado es incorrecto, <b>aparecerá el siguiente mensaje:</b><br><br>';
				echo '       <div class="alert alert-danger alert-dismissible fade in">';
                echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '           <center>¡Archivo inválido!, No se cargaron los datos </center>';
                echo '       </div>';
                echo 'ó bien si el archivo tiene datos dúplicados, <b>aparecerá esté otro mensaje:</b><br><br>';
                echo '       <div class="alert alert-danger alert-dismissible fade in">';
                echo '          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '          <center>¡Archivo inválido! No cumple con el formato indicado ó hay datos dúplicados (los datos no dúplicados si se guardaran)</center>';
                echo '       </div>';
				echo '      </div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse12"><b>Ver alumno</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse12" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para ver la información del alumno:<br>';
				echo '        <b>Paso 1.-</b>Ir a la pestaña <button class="button button1">Alumnos</button><br><br>';
				echo '        <b>Paso 2.-</b>Dar clic en el icono ver ';
				echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal" style="color:#2A9AFE" data-target="#error_logueo">';
                echo '            <i class="fa fa-search" aria-hidden="true"></i>';
                echo '        </button>';
				echo '   <br><br>Se desplegará una ventana donde se podrán visualizar los datos completos del alumno.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse13"><b>Editar alumno</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse13" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para editar un <b> Alumno </b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Alumnos</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Editar (Al deslizar el mouse en  el formulario alumnos aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Editar</b> ';
			    echo            '<i class="fa fa-pencil-square-o fa-1x" aria-hidden="true" style="color:#2E9AFE;"></i><br><br>';			
				echo '        <b>Paso 3.-</b> Aparcerá el formulario </b><b>ACTUALIZAR ALUMNO</b>, modifica el dato que deseas actualizar<br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Actualizar</button> (Si es que se desea actualizar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar </button>(Si es que no se desean guardar los datos).<br><br>';
				echo '        <font color="gray">Si los datos ingresados fueron correctos</font>, aparecerá el siguiente mensaje: <br><br>';
				echo '		  <div class="alert alert-success alert-dismissible">';
                echo '          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '            <center>Datos editados correctamente</center>';
                echo '        </div>';
				echo '     Una vez enviada la actualización, se podrán visualizar los datos actualizados en el sistema web.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse14"><b>Eliminar alumno</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse14" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para eliminar un <b> Alumno </b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Alumnos</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Eliminar (Al deslizar el mouse en  el formulario alumnos aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Eliminar</b>';
                echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal"  style="color:#2E9AFE;" data-target='.'"'."#"."eliminar_alumno".$idalumno.'" '.'>';
		        echo '           <i class="fa fa-trash-o fa-2x" aria-hidden="true" style="color:#2E9AFE;"></i><br>';
				echo '        </button>';
				echo '        <br><br><b>Paso 3.-</b> Aparcerá el formulario </b><b>ELIMINAR ALUMNO</b> con el siguiente mensaje: <b>¿Está seguro de eliminar este número de control?</b>,<font color="blue"> Una vez eliminado no se podrá recuperar.</font><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Eliminar</button> (Si es que se desea eliminar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desea eliminar el alumno).<br><br>';
				echo '        <font color="gray">Si se acepto la eliminación del alumno</font>, aparecerá el siguiente mensaje:<br><br>';
                echo '        <div class="alert alert-success alert-dismissible">';
                echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '             <center>Alumno eliminado correctamente<center>';
                echo '        </div>';
		        echo '        Una vez eliminado el alumno, no existirá registro de él.</div>';
				echo '      </div>';
				echo '    </div>';
				echo '    </div>';
				echo'</div>';
				echo '<br>';
				
				echo '<div class="panel panel-success">';
                echo '    <div class="panel panel-success">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse15"><div class="panel-heading">Menú de Ayuda <i class="fa fa-question-circle" aria-hidden="true"></i> (Historial Académico del alumno) <i class="fa fa-history fa-2x" aria-hidden="true"></i>       <center><i class="fa fa-angle-down" aria-hidden="true"> Desglosa aquí</i></center></div></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse15" class="panel-collapse collapse">';
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse16"><b>Agregar historial (Académico)</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse16" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para agregar el <b> Historial Académico </b> de un alumno:<br><br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Historial Académico</button><br><br>';
				echo '        <b>Paso 2.-</b> Ir al botón   <button type="button" class="btn btn-default"><font color="green"><i class="fa fa-plus-circle fa-1x" aria-hidden="true"> Agregar Historial</i></font></button><br><br>';
				echo '        <b>Paso 3.-</b> Llenar el formulario </b><b>NUEVO HISTORIAL</b><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Guardar</button> (Si es que se desea guardar) ó bien  en el botón   <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desean guardar los datos).<br><br>';
				echo '        Si los datos ingresados fueron correctos, <b>aparecerá el siguiente mensaje:</b><br><br>';
	            echo '        <div class="alert alert-success alert-dismissible fade in">';
                echo '            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '            <center>El historial del alumno fue guardado correctamente</center>';
                echo '        </div>				';
                echo '       <font color="gray">Una vez enviado esté mensaje, se podrán visualizar los datos del historial académico del alumno agregado en el sistema web.</font></div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse17"><b>Búsqueda historial (Académico)</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse17" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para la realización de una búsqueda ';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Historial Académico</button><br><br><br>';
				echo '        <b>Paso 2.-</b> Posicionar el mouse en la caja de búsqueda <input type="text" placeholder="BUSCAR..."><br><br>';
				echo '        <b>Paso 3.-</b> Posicionar el mouse a mano derecha y seleccionar el tipo de búsqueda'; 
                echo '      <select>';
				echo '			  <option value="idcontrol">No. Control</option>';
				echo '			  <option value="semestre">Semestre</option>';
				echo '            <option value="seguro_facultativo">Seguro facultativo</option>';
				echo '     		  <option value="creditos_actuales">Créditos actuales</option>';
				echo '	     	  <option value="situacion_alumno">Situación del alumno</option>';
				echo '	       	  <option value="clave_tipoalu">Tipo de alumno</option>';
				echo '			</select>
				(No. Control, Semestre, Seguro facultativo, Créditos actuales, Situación del alumno, Tipo de alumno)<br><br>';
				echo '        <b>Paso 4.-</b> Introducir el dato a buscar <br><br>Si el dato que se introdujo en la caja de búsqueda es correcto regresara el dato buscado.<br><br>Si el dato que se introdujo en la caja de búsqueda es incorrecto, se mostrará un mensaje de error (De acuerdo al dato de búsqueda).</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse18"><b>Ver historial (Académico)</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse18" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para ver la información del <b>Historial Académico</b> de un alumno:<br>';
				echo '        <b>Paso 1.-</b>Ir a la pestaña <button class="button button1">Historial Académico</button><br><br>';
				echo '        <b>Paso 2.-</b>Dar clic en el icono ver ';
				echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal" style="color:#2A9AFE" data-target="#error_logueo">';
                echo '            <i class="fa fa-search" aria-hidden="true"></i>';
                echo '        </button>';
				echo '   <br><br>Se desplegará una ventana donde se podrán visualizar los datos completos del historial académico del alumno.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse19"><b>Editar historial (Académico)</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse19" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para editar el <b>Historial Académico</b> de un alumno:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Historial Académico</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Editar (Al deslizar el mouse en  el formulario historial académico aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Editar</b> ';
			    echo            '<i class="fa fa-pencil-square-o fa-1x" aria-hidden="true" style="color:#2E9AFE;"></i><br><br>';			
				echo '        <b>Paso 3.-</b> Aparcerá el formulario </b><b>ACTUALIZAR HISTORIAL</b>, modifica el dato que deseas actualizar<br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Actualizar</button> (Si es que se desea actualizar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar </button>(Si es que no se desean guardar los datos).<br><br>';
				echo '        <font color="gray">Si los datos ingresados fueron correctos</font>, aparecerá el siguiente mensaje: <br><br>';
				echo '		  <div class="alert alert-success alert-dismissible">';
                echo '          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '            <center>Datos editados correctamente</center>';
                echo '        </div>';
				echo '     Una vez enviada la actualización, se podrán visualizar los datos actualizados del historial académico del alumno en el sistema web.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse20"><b>Eliminar historial (Académico)</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse20" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para eliminar el <b>Historial Académico</b> de un alumno:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Historial Académico</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Eliminar (Al deslizar el mouse en  el formulario historial académico aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Eliminar</b>';
                echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal"  style="color:#2E9AFE;" data-target='.'"'."#"."eliminar_alumno".$idalumno.'" '.'>';
		        echo '           <i class="fa fa-trash-o fa-2x" aria-hidden="true" style="color:#2E9AFE;"></i><br>';
				echo '        </button>';
				echo '        <br><br><b>Paso 3.-</b> Aparcerá el formulario </b><b>ELIMINAR HISTORIAL</b> con el siguiente mensaje: <b>¿Está seguro de eliminar éste historial?</b>,<font color="blue"> Una vez eliminado no se podrá recuperar.</font><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Eliminar</button> (Si es que se desea eliminar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desea eliminar el Historial Académico).<br><br>';
				echo '        <font color="gray">Si se acepto la eliminación del Historial Académico</font>, aparecerá el siguiente mensaje:<br><br>';
                echo '        <div class="alert alert-success alert-dismissible">';
                echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '             <center>El historial académico del alumno eliminado correctamente<center>';
                echo '        </div>';
		        echo '        Una vez eliminado el historial académico del alumno, no existirá registro de él.</div>';
				echo '      </div>';
				echo '    </div>';
				echo '</div>';
				echo '<br>';
				
				echo '<div class="panel panel-warning">';
                echo '    <div class="panel panel-warning">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse21"><div class="panel-heading">Menú de Ayuda <i class="fa fa-question-circle" aria-hidden="true"></i> (Empresa) <i class="fa fa-building fa-2x" aria-hidden="true"></i>       <center><i class="fa fa-angle-down" aria-hidden="true"> Desglosa aquí</i></center></div></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse21" class="panel-collapse collapse">';
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse22"><b>Agregar empresa</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse22" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para agregar una <b> Empresa </b>:<br><br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Empresas</button><br><br>';
				echo '        <b>Paso 2.-</b> Ir al botón   <button type="button" class="btn btn-default"><font color="green"><i class="fa fa-plus-circle fa-1x" aria-hidden="true"> Agregar Empresa</i></font></button><br><br>';
				echo '        <b>Paso 3.-</b> Llenar el formulario </b><b>NUEVA EMPRESA FOLIO No.:</b><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Guardar</button> (Si es que se desea guardar) ó bien  en el botón   <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desean guardar los datos).<br><br>';
				echo '        Si los datos ingresados fueron correctos, <b>aparecerá el siguiente mensaje:</b><br><br>';
	            echo '        <div class="alert alert-success alert-dismissible fade in">';
                echo '            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '            <center> Empresa guardada correctamente </center>';
                echo '        </div>				';
                echo '       <font color="gray">Una vez enviado esté mensaje, se podrán visualizar los datos de la empresa agregada en el sistema web.</font></div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse23"><b>Búsqueda empresa</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse23" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para la realización de una búsqueda<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Empresas</button><br><br>';
				echo '        <b>Paso 2.-</b> Posicionar el mouse en la caja de búsqueda <input type="text" placeholder="BUSCAR..."><br><br>';
				echo '        <b>Paso 3.-</b> Posicionar el mouse a mano derecha y seleccionar el tipo de búsqueda'; 
                echo '      <select>';
				echo '         <option value="idempresa">Folio</option>';
				echo ' 		   <option value="nombre">Empresa</option>';
				echo '	       <option value="rfc">RFC</option>';
				echo '		   <option value="razon_social">Razón social</option>';
				echo '		   <option value="nombre_sector">Tipo sector</option>';
				echo '		   <option value="nombre_giro">Giro Comercial</option>';
				echo '		</select>
				(Folio, Empresa, RFC, Razón social, Tipo sector, Giro comercial)<br><br>';
				echo '        <b>Paso 4.-</b> Introducir el dato a buscar <br><br>Si el dato que se introdujo en la caja de búsqueda es correcto regresara el dato buscado.<br><br>Si el dato que se introdujo en la caja de búsqueda es incorrecto, se mostrará un mensaje de error (De acuerdo al dato de búsqueda).</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse24"><b>Ver empresa</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse24" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para ver la información del Empresas:<br>';
				echo '        <b>Paso 1.-</b>Ir a la pestaña <button class="button button1">Empresas</button><br><br>';
				echo '        <b>Paso 2.-</b>Dar clic en el icono ver ';
				echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal" style="color:#2A9AFE" data-target="#error_logueo">';
                echo '            <i class="fa fa-search" aria-hidden="true"></i>';
                echo '        </button>';
				echo '   <br><br>Se desplegará una ventana donde se podrán visualizar los datos completos de la empresa.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse25"><b>Editar empresa</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse25" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para editar una <b> Empresa </b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Empresas</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Editar (Al deslizar el mouse en  el formulario empresa aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Editar</b> ';
			    echo            '<i class="fa fa-pencil-square-o fa-1x" aria-hidden="true" style="color:#2E9AFE;"></i><br><br>';			
				echo '        <b>Paso 3.-</b> Aparcerá el formulario </b><b>ACTUALIZAR EMPRESA</b>, modifica el dato que deseas actualizar<br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Actualizar</button> (Si es que se desea actualizar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar </button>(Si es que no se desean guardar los datos).<br><br>';
				echo '        <font color="gray">Si los datos ingresados fueron correctos</font>, aparecerá el siguiente mensaje: <br><br>';
				echo '		  <div class="alert alert-success alert-dismissible">';
                echo '          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '            <center>Datos editados correctamente</center>';
                echo '        </div>';
				echo '     Una vez enviada la actualización, se podrán visualizar los datos actualizados de la empresa en el sistema web.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse26"><b>Eliminar empresa</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse26" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para eliminar una <b>Empresa</b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Empresas</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Eliminar (Al deslizar el mouse en  el formulario empresa aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Eliminar</b>';
                echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal"  style="color:#2E9AFE;" data-target='.'"'."#"."eliminar_empresa".$idempresa.'" '.'>';
		        echo '           <i class="fa fa-trash-o fa-2x" aria-hidden="true" style="color:#2E9AFE;"></i><br>';
				echo '        </button>';
				echo '        <br><br><b>Paso 3.-</b> Aparcerá el formulario </b><b>ELIMINAR EMPRESA</b> con el siguiente mensaje: <b>¿Está seguro de eliminar esta empresa?</b>,<font color="blue"> Una vez eliminada no se podrá recuperar.</font><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Eliminar</button> (Si es que se desea eliminar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desea eliminar la empresa).<br><br>';
				echo '        <font color="gray">Si se acepto la eliminación de la Empresa</font>, aparecerá el siguiente mensaje:<br><br>';
                echo '        <div class="alert alert-success alert-dismissible">';
                echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '             <center>Empresa eliminada correctamente<center>';
                echo '        </div>';
		        echo '        Una vez eliminada la empresa, no existirá registro de ella.</div>';
				echo '      </div>';
				echo '    </div>';
				echo '</div>';
				echo '<br>';
				
				echo '<div class="panel panel-primary">';
                echo '    <div class="panel panel-primary">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse27"><div class="panel-heading">Menú de Ayuda <i class="fa fa-question-circle" aria-hidden="true"></i> (Departamento) <i class="fa fa-user fa-2x" aria-hidden="true"></i>       <center><i class="fa fa-angle-down" aria-hidden="true"> Desglosa aquí</i></center></div></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse27" class="panel-collapse collapse">';
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse28"><b>Agregar departamento</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse28" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para agregar un <b>Departamento</b>:<br><br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Departamentos</button><br><br>';
				echo '        <b>Paso 2.-</b> Ir al botón   <button type="button" class="btn btn-default"><font color="green"><i class="fa fa-plus-circle fa-1x" aria-hidden="true"> Agregar Responsable</i></font></button><br><br>';
				echo '        <b>Paso 3.-</b> Llenar el formulario </b><b>NUEVO DEPARTAMENTO</b><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Guardar</button> (Si es que se desea guardar) ó bien  en el botón   <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desean guardar los datos).<br><br>';
				echo '        Si los datos ingresados fueron correctos, <b>aparecerá el siguiente mensaje:</b><br><br>';
	            echo '        <div class="alert alert-success alert-dismissible fade in">';
                echo '            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '            <center> Departamento guardado correctamente </center>';
                echo '        </div>				';
                echo '       <font color="gray">Una vez enviado esté mensaje, se podrán visualizar los datos del departamento agregado en el sistema web.</font></div>';
				echo '      </div>';
				echo '    </div>';
				
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse29"><b>Búsqueda de departamento</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse29" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para la realización de una búsqueda<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Departamentos</button><br><br>';
				echo '        <b>Paso 2.-</b> Posicionar el mouse en la caja de búsqueda <input type="text" placeholder="BUSCAR..."><br><br>';
				echo '        <b>Paso 3.-</b> Posicionar el mouse a mano derecha y seleccionar el tipo de búsqueda'; 
                echo '      <select>';
				echo '           <option value="nombre_empresa">Empresa</option>';
				echo '   	     <option value="nombre">Nombre</option>';
				echo '   		 <option value="ap">Apellido Paterno</option>';
				echo '  		 <option value="am">Apellido Materno</option>';
				echo '  		 <option value="nombre_departamento">Departamento</option>';
				echo '		</select>
				(Empresa, Nombre, Apellido Paterno, Apellido Materno, Departamento)<br><br>';
				echo '        <b>Paso 4.-</b> Introducir el dato a buscar <br><br>Si el dato que se introdujo en la caja de búsqueda es correcto regresara el dato buscado.<br><br>Si el dato que se introdujo en la caja de búsqueda es incorrecto, se mostrará un mensaje de error (De acuerdo al dato de búsqueda).</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse29"><b>Ver departamento</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse29" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para ver la información del Departamento:<br>';
				echo '        <b>Paso 1.-</b>Ir a la pestaña <button class="button button1">Departamentos</button><br><br>';
				echo '        <b>Paso 2.-</b>Dar clic en el icono ver ';
				echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal" style="color:#2A9AFE" data-target="#error_logueo">';
                echo '            <i class="fa fa-search" aria-hidden="true"></i>';
                echo '        </button>';
				echo '   <br><br>Se desplegará una ventana donde se podrán visualizar los datos completos del departamento.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse30"><b>Editar departamento</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse30" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para editar un <b>departamento </b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Departamentos</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Editar (Al deslizar el mouse en  el formulario departamentos en donde aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Editar</b> ';
			    echo            '<i class="fa fa-pencil-square-o fa-1x" aria-hidden="true" style="color:#2E9AFE;"></i><br><br>';			
				echo '        <b>Paso 3.-</b> Aparcerá el formulario </b><b>ACTUALIZAR DEPARTAMENTO</b>, modifica el dato que deseas actualizar<br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Actualizar</button> (Si es que se desea actualizar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar </button>(Si es que no se desean guardar los datos).<br><br>';
				echo '        <font color="gray">Si los datos ingresados fueron correctos</font>, aparecerá el siguiente mensaje: <br><br>';
				echo '		  <div class="alert alert-success alert-dismissible">';
                echo '          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '            <center>Datos editados correctamente</center>';
                echo '        </div>';
				echo '     Una vez enviada la actualización, se podrán visualizar los datos actualizados del departamento en el sistema web.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse31"><b>Eliminar departamento</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse31" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para eliminar un <b>Departamento</b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Departamentos</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Eliminar (Al deslizar el mouse en  el formulario solicitud aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Eliminar</b>';
                echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal"  style="color:#2E9AFE;" data-target='.'"'."#"."eliminar_empresa".$idempresa.'" '.'>';
		        echo '           <i class="fa fa-trash-o fa-2x" aria-hidden="true" style="color:#2E9AFE;"></i><br>';
				echo '        </button>';
				echo '        <br><br><b>Paso 3.-</b> Aparcerá el formulario </b><b>ELIMINAR DEPARTAMENTO</b> con el siguiente mensaje: <b>¿Está seguro de eliminar este departamento?</b>,<font color="blue"> Una vez eliminado no se podrá recuperar.</font><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Eliminar</button> (Si es que se desea eliminar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desea eliminar el departamento).<br><br>';
				echo '        <font color="gray">Si se acepto la eliminación del departamento</font>, aparecerá el siguiente mensaje:<br><br>';
                echo '        <div class="alert alert-success alert-dismissible">';
                echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '             <center>Departamento eliminado correctamente<center>';
                echo '        </div>';
		        echo '        Una vez eliminado el departamento, no existirá registro de él.</div>';
				echo '      </div>';
				echo '    </div>';
				echo '</div>';
				echo '<br>';
				
				echo '<div class="panel panel-success">';
                echo '    <div class="panel panel-success">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse32"><div class="panel-heading">Menú de Ayuda <i class="fa fa-question-circle" aria-hidden="true"></i> (Solicitud) <i class="fa fa-sticky-note fa-2x" aria-hidden="true"></i>       <center><i class="fa fa-angle-down" aria-hidden="true"> Desglosa aquí</i></center></div></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse32" class="panel-collapse collapse">';
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse33"><b>Agregar solicitud</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse33" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para agregar una <b>Solicitud</b>:<br><br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Solicitudes</button><br><br>';
				echo '        <b>Paso 2.-</b> Ir al botón   <button type="button" class="btn btn-default"><font color="green"><i class="fa fa-plus-circle fa-1x" aria-hidden="true"> Agregar Solicitud</i></font></button><br><br>';
				echo '        <b>Paso 3.-</b> Llenar el formulario </b><b>NUEVA SOLICITUD FOLIO No.:</b><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Guardar</button> (Si es que se desea guardar) ó bien  en el botón   <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desean guardar los datos de la solicitud).<br><br>';
				echo '        Si los datos ingresados fueron correctos, <b>aparecerá el siguiente mensaje:</b><br><br>';
	            echo '        <div class="alert alert-success alert-dismissible fade in">';
                echo '            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '            <center> Solicitud guardada correctamente </center>';
                echo '        </div>				';
                echo '       <font color="gray">Una vez enviado esté mensaje, se podrán visualizar los datos de la solicitud agregada en el sistema web.</font></div>';
				echo '      </div>';
				echo '    </div>';
				
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse34"><b>Búsqueda solicitud</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse34" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para la realización de una búsqueda ';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Solicitudes</button><br><br><br>';
				echo '        <b>Paso 2.-</b> Posicionar el mouse en la caja de búsqueda <input type="text" placeholder="BUSCAR..."><br><br>';
				echo '        <b>Paso 3.-</b> Posicionar el mouse a mano derecha y seleccionar el tipo de búsqueda'; 
                echo '      <select>';
				echo '          <option value="folio">Folio</option>';
                echo '          <option value="empresa">Empresa</option>';                       
                echo '          <option value="prestamo">Tipo de servicio</option>';
                echo '          <option value="division">División</option>';
                echo '          <option value="status">Situación</option>';
				echo '			</select>
				(Folio, Empresa, Tipo de servicio, División, Situación)<br><br>';
				echo '        <b>Paso 4.-</b> Introducir el dato a buscar <br><br>Si el dato que se introdujo en la caja de búsqueda es correcto regresara el dato buscado.<br><br>Si el dato que se introdujo en la caja de búsqueda es incorrecto, se mostrará un mensaje de error (De acuerdo al dato de búsqueda).</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse35"><b>Ver solicitud</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse35" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para ver la información del Solicitud:<br>';
				echo '        <b>Paso 1.-</b>Ir a la pestaña <button class="button button1">Solicitudes</button><br><br>';
				echo '        <b>Paso 2.-</b>Dar clic en el icono ver ';
				echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal" style="color:#2A9AFE" data-target="#error_logueo">';
                echo '            <i class="fa fa-search" aria-hidden="true"></i>';
                echo '        </button>';
				echo '   <br><br>Se desplegará una ventana donde se podrán visualizar los datos completos de la solicitud agregada.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse36"><b>Editar solicitud</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse36" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para editar una <b> Solicitud </b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Solicitudes</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Editar (Al deslizar el mouse en  el formulario solicitud aparecerá una selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Editar</b> ';
			    echo            '<i class="fa fa-pencil-square-o fa-1x" aria-hidden="true" style="color:#2E9AFE;"></i><br><br>';			
				echo '        <b>Paso 3.-</b> Aparcerá el formulario </b><b>ACTUALIZAR SOLICITUD</b>, modifica el dato que deseas actualizar<br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Actualizar</button> (Si es que se desea actualizar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar </button>(Si es que no se desean guardar los datos).<br><br>';
				echo '        <font color="gray">Si los datos ingresados fueron correctos</font>, aparecerá el siguiente mensaje: <br><br>';
				echo '		  <div class="alert alert-success alert-dismissible">';
                echo '          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '            <center>Datos editados correctamente</center>';
                echo '        </div>';
				echo '     Una vez enviada la actualización, se podrán visualizar los datos actualizados de la solicitud en el sistema web.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse37"><b>Eliminar solicitud</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse37" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para eliminar una <b>Solicitud</b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Solicitudes</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Eliminar (Al deslizar el mouse en  el formulario solicitud aparecerá una selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Eliminar</b>';
                echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal"  style="color:#2E9AFE;" data-target='.'"'."#"."eliminar_empresa".$idempresa.'" '.'>';
		        echo '           <i class="fa fa-trash-o fa-2x" aria-hidden="true" style="color:#2E9AFE;"></i><br>';
				echo '        </button>';
				echo '        <br><br><b>Paso 3.-</b> Aparcerá el formulario </b><b>ELIMINAR SOLICITUD</b> con el siguiente mensaje: <b>¿Está seguro de eliminar esta solicitud?</b>,<font color="blue"> Una vez eliminada no se podrá recuperar.</font><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Eliminar</button> (Si es que se desea eliminar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desea eliminar la solicitud).<br><br>';
				echo '        <font color="gray">Si se acepto la eliminación del Solicitud</font>, aparecerá el siguiente mensaje:<br><br>';
                echo '        <div class="alert alert-success alert-dismissible">';
                echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
                echo '             <center>Solicitud eliminada correctamente<center>';
                echo '        </div>';
		        echo '        Una vez eliminada esta solicitud, no existirá registro de ella.</div>';
				echo '      </div>';
				echo '    </div>';
				echo '  </div> ';
				echo '<br>';
				
				echo '<div class="panel panel-warning">';
                echo '    <div class="panel panel-warning">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse38"><div class="panel-heading">Menú de Ayuda <i class="fa fa-question-circle" aria-hidden="true"></i> (Materias) <i class="fa fa-list fa-2x" aria-hidden="true"></i>       <center><i class="fa fa-angle-down" aria-hidden="true"> Desglosa aquí</i></center></div></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '    <div id="collapse38" class="panel-collapse collapse">';
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse39"><b>Agregar materia</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse39" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para agregar una <b> Materia </b>:<br><br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Materias</button><br><br>';
				echo '        <b>Paso 2.-</b> Ir al botón   <button type="button" class="btn btn-default"><font color="green"><i class="fa fa-plus-circle fa-1x" aria-hidden="true"> Agregar Materia</i></font></button><br><br>';
				echo '        <b>Paso 3.-</b> Llenar el formulario </b><b>NUEVA MATERIA</b><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Guardar</button> (Si es que se desea guardar) ó bien  en el botón   <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desean guardar los datos).<br><br>';
				echo '        Si los datos ingresados fueron correctos, <b>aparecerá el siguiente mensaje:</b><br><br>';
				echo '        <div class="alert alert-success alert-dismissible fade in">';
				echo '            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
				echo '            <center> Materia guardada correctamente</center>';
				echo '        </div>				';
				echo '       <font color="gray">Una vez enviado esté mensaje, se podrán visualizar los datos de la materia agregada en el sistema web.</font></div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse40"><b>Importar una lista de materias</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse40" class="panel-collapse collapse">';
                echo '        <div class="panel-body">Si usted tiene una larga lista de Materias y no los quiere llenar manualmente en el sistema (le tenemos una solución, Importar una lista de Materias en excel)<br><br>';
				echo '        Pasos para importar una <b> Lista de Materias </b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Materias</button><br><br>';	
				echo '        <b>Paso 2.-</b> Dar clic en el botón <div class="well"><center><font color="blue">¿Deseas importar una lista de Materias?, Desglosa aquí aquí</font></center></div>';
				echo '        <b><font color="grey">Una vez que haya dado clic se desplazará un ventana informativa</font></b>, en donde se podrá <b><font color="green"><i class="fa fa-download" aria-hidden="true"> </i></font><font color="blue"> Descargar plantilla </font></b><b>(materia.csv)</b><br><br></font>';
				echo '        <b>Paso 3.-</b> Abrir la plantilla <b>materia.csv</b> y llenarla con los datos requeridos en la parte superior del archivo (En la parte izquierda viene un ejemplo)<br><br></b>';
				echo '        Una vez que todos los capos hayan sido llenados se le da guardar al archivo <b>(materia.csv)</b> y nos regresamos al formulario de la materias <br><br></b>';
				echo '        <b>Paso 4.-</b> Seleccionamos el botón <b>Seleccionar archivo</b>, El cual desplegará una ventana de búsqueda, seleccionamos el archivo <b>(materia.csv)</b><br><br>';
				echo '        <b>Paso 5.-</b> Damos clic en abrir (Una vez hecho estó se cargara el nombre del archivo )<br><br>';
				echo '        <b>Paso 6.-</b> Dar clic en el botón <button type="button"><font color="green">Cargar</font></button><br><br>';
				echo '        Si los datos ingresados fueron correctos, <b>aparecerá el siguiente mensaje:</b> <br><br>';
				echo '       <div class="alert alert-success alert-dismissible fade in">';
				echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
				echo '             <center>Archivo importado correctamente</center>';
				echo '       </div>';
				echo '  <font color="gray">Una vez enviado esté mensaje, se podrán visualizar los datos de la materia agregada en el sistema web.</font><br><br>';
				echo '       Si el archivo importado es incorrecto, <b>aparecerá el siguiente mensaje:</b><br><br>';
				echo '       <div class="alert alert-danger alert-dismissible fade in">';
				echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
				echo '           <center>¡Archivo inválido!, No se cargaron los datos </center>';
				echo '       </div>';
				echo 'ó bien si el archivo tiene datos dúplicados, <b>aparecerá esté otro mensaje:</b><br><br>';
				echo '       <div class="alert alert-danger alert-dismissible fade in">';
				echo '          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
				echo '          <center>¡Archivo inválido! No cumple con el formato indicado ó hay datos dúplicados (los datos no dúplicados si se guardaran)</center>';
				echo '       </div>';
				echo '      </div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse41"><b>Búsqueda de materias</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse41" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para la realización de una búsqueda ';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Materias</button><br><br>';
				echo '        <b>Paso 2.-</b> Posicionar el mouse en la caja de búsqueda <input type="text" placeholder="BUSCAR..."><br><br>';
				echo '        <b>Paso 3.-</b> Posicionar el mouse a mano derecha y seleccionar el tipo de búsqueda'; 
                echo '      <select>';
				echo '        <option value="clave">Clave materia</option>';
                echo '        <option value="nombre">Nombre</option>';
				echo '			</select>
				(Clave materia, Nombre)<br><br>';
				echo '        <b>Paso 4.-</b> Introducir el dato a buscar <br><br>Si el dato que se introdujo en la caja de búsqueda es correcto regresara el dato buscado.<br><br>Si el dato que se introdujo en la caja de búsqueda es incorrecto, se mostrará un mensaje de error (De acuerdo al dato de búsqueda).</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse42"><b>Ver materia</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse42" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para ver la información del materia:<br>';
			    echo '        <b>Paso 1.-</b>Ir a la pestaña <button class="button button1">Materias</button><br><br>';
				echo '        <b>Paso 2.-</b>Dar clic en el icono ver ';
				echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal" style="color:#2A9AFE" data-target="#error_logueo">';
				echo '            <i class="fa fa-search" aria-hidden="true"></i>';
				echo '        </button>';
				echo '   <br><br>Se desplegará una ventana donde se podrán visualizar los datos completos de la materia.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse43"><b>Editar materia</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse43" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para editar una <b> materia </b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Materias</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Editar (Al deslizar el mouse en  el formulario materias aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Editar</b> ';
				echo            '<i class="fa fa-pencil-square-o fa-1x" aria-hidden="true" style="color:#2E9AFE;"></i><br><br>';			
				echo '        <b>Paso 3.-</b> Aparcerá el formulario </b><b>ACTUALIZAR MATERIA</b>, modifica el dato que deseas actualizar<br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Actualizar</button> (Si es que se desea actualizar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar </button>(Si es que no se desean guardar los datos).<br><br>';
				echo '        <font color="gray">Si los datos ingresados fueron correctos</font>, aparecerá el siguiente mensaje: <br><br>';
				echo '		  <div class="alert alert-success alert-dismissible">';
				echo '          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
				echo '            <center>Datos editados correctamente</center>';
				echo '        </div>';
				echo '     Una vez enviada la actualización, se podrán visualizar los datos actualizados en el sistema web.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse44"><b>Eliminar materia</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse44" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para eliminar una <b>materia</b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Materias</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Eliminar (Al deslizar el mouse en  el formulario materias aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Eliminar</b>';
				echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal"  style="color:#2E9AFE;" data-target='.'"'."#"."eliminar_materia".$idmateria.'" '.'>';
				echo '           <i class="fa fa-trash-o fa-2x" aria-hidden="true" style="color:#2E9AFE;"></i><br>';
				echo '        </button>';
				echo '        <br><br><b>Paso 3.-</b> Aparcerá el formulario </b><b>ELIMINAR MATERIA</b> con el siguiente mensaje: <b>¿Está seguro de eliminar esta materia?</b>,<font color="blue"> Una vez eliminada no se podrá recuperar.</font><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Eliminar</button> (Si es que se desea eliminar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desea eliminar la materia).<br><br>';
				echo '        <font color="gray">Si se acepto la eliminación del materia</font>, aparecerá el siguiente mensaje:<br><br>';
				echo '        <div class="alert alert-success alert-dismissible">';
				echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
				echo '             <center>Materia eliminada correctamente<center>';
				echo '        </div>';
				echo '        Una vez eliminada la materia, no existirá registro de ella.</div>';
				echo '      </div>';
				echo '    </div>';
				echo'</div>';
				echo '<br>';
				
				echo '<div class="panel panel-primary">';
                echo '    <div class="panel panel-primary">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse45"><div class="panel-heading">Menú de Ayuda <i class="fa fa-question-circle" aria-hidden="true"></i> (Especialidad) <i class="fa fa-star fa-2x" aria-hidden="true"></i>       <center><i class="fa fa-angle-down" aria-hidden="true"> Desglosa aquí</i></center></div></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse45" class="panel-collapse collapse">';
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse46"><b>Agregar especialidad</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse46" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para agregar una <b> Especialidad </b>:<br><br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Especialidad</button><br><br>';
				echo '        <b>Paso 2.-</b> Ir al botón   <button type="button" class="btn btn-default"><font color="green"><i class="fa fa-plus-circle fa-1x" aria-hidden="true"> Agregar Especialidad</i></font></button><br><br>';
				echo '        <b>Paso 3.-</b> Llenar el formulario </b><b>NUEVA ESPECIALIDAD</b><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Guardar</button> (Si es que se desea guardar) ó bien  en el botón   <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desean guardar los datos).<br><br>';
				echo '        Si los datos ingresados fueron correctos, <b>aparecerá el siguiente mensaje:</b><br><br>';
				echo '        <div class="alert alert-success alert-dismissible fade in">';
				echo '            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
				echo '            <center> Especialidad guardada correctamente</center>';
				echo '        </div>				';
				echo '       <font color="gray">Una vez enviado esté mensaje, se podrán visualizar los datos de la especialidad agregada en el sistema web.</font></div>';
				echo '      </div>';
				echo '    </div>';
				
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse47"><b>Búsqueda de especialidad</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse47" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para la realización de una búsqueda<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Especialidad</button><br><br>';
				echo '        <b>Paso 2.-</b> Posicionar el mouse en la caja de búsqueda <input type="text" placeholder="BUSCAR..."><br><br>';
				echo '        <b>Paso 3.-</b> Posicionar el mouse a mano derecha y seleccionar el tipo de búsqueda'; 
                echo '      <select>';
				echo '           <option value="clave">Clave</option>';
				echo '   	     <option value="nombre">Nombre</option>';
				echo '   		 <option value="descripcion">Descripción</option>';
				echo '		</select>
				(Clave, Nombre, Descripción)<br><br>';
				echo '        <b>Paso 4.-</b> Introducir el dato a buscar <br><br>Si el dato que se introdujo en la caja de búsqueda es correcto regresara el dato buscado.<br><br>Si el dato que se introdujo en la caja de búsqueda es incorrecto, se mostrará un mensaje de error (De acuerdo al dato de búsqueda).</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse48"><b>Ver especialidad</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse48" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para ver la información de la Especialidad:<br>';
				echo '        <b>Paso 1.-</b>Ir a la pestaña <button class="button button1">Especialidad</button><br><br>';
				echo '        <b>Paso 2.-</b>Dar clic en el icono ver ';
				echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal" style="color:#2A9AFE" data-target="#error_logueo">';
				echo '            <i class="fa fa-search" aria-hidden="true"></i>';
				echo '        </button>';
				echo '   <br><br>Se desplegará una ventana donde se podrán visualizar los datos completos de la especialidad.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse49"><b>Editar especialidad</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse49" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para editar una <b> Especialidad </b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Especialidad</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Editar (Al deslizar el mouse en  el formulario especialidad aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Editar</b> ';
				echo            '<i class="fa fa-pencil-square-o fa-1x" aria-hidden="true" style="color:#2E9AFE;"></i><br><br>';			
				echo '        <b>Paso 3.-</b> Aparcerá el formulario </b><b>ACTUALIZAR ESPECIALIDAD</b>, modifica el dato que deseas actualizar<br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Actualizar</button> (Si es que se desea actualizar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar </button>(Si es que no se desean guardar los datos).<br><br>';
				echo '        <font color="gray">Si los datos ingresados fueron correctos</font>, aparecerá el siguiente mensaje: <br><br>';
				echo '		  <div class="alert alert-success alert-dismissible">';
				echo '          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
				echo '            <center>Datos editados correctamente</center>';
				echo '        </div>';
				echo '     Una vez enviada la actualización, se podrán visualizar los datos actualizados en el sistema web.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse50"><b>Eliminar especialidad</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse50" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para eliminar una <b>Especialidad</b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Especialidad</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Eliminar (Al deslizar el mouse en  el formulario especialidad aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Eliminar</b>';
				echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal"  style="color:#2E9AFE;" data-target='.'"'."#"."eliminar_materia".$idmateria.'" '.'>';
				echo '           <i class="fa fa-trash-o fa-2x" aria-hidden="true" style="color:#2E9AFE;"></i><br>';
				echo '        </button>';
				echo '        <br><br><b>Paso 3.-</b> Aparcerá el formulario </b><b>ELIMINAR ESPECIALIDAD</b> con el siguiente mensaje: <b>¿Está seguro de eliminar esta especialidad?</b>,<font color="blue"> Una vez eliminada no se podrá recuperar.</font><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Eliminar</button> (Si es que se desea eliminar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desea eliminar la especialidad).<br><br>';
				echo '        <font color="gray">Si se acepto la eliminación del Especialidad</font>, aparecerá el siguiente mensaje:<br><br>';
				echo '        <div class="alert alert-success alert-dismissible">';
				echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
				echo '             <center>Especialidad eliminada correctamente<center>';
				echo '        </div>';
				echo '        Una vez eliminada la especialidad, no existirá registro de ella.</div>';
				echo '      </div>';
				echo '    </div>';
				echo '</div>';
				echo '<br>';
				
				echo '<div class="panel panel-success">';
                echo '    <div class="panel panel-success">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse51"><div class="panel-heading">Menú de Ayuda <i class="fa fa-question-circle" aria-hidden="true"></i> (Especialidad materia) <i class="fa fa-graduation-cap fa-2x" aria-hidden="true"></i>       <center><i class="fa fa-angle-down" aria-hidden="true"> Desglosa aquí</i></center></div></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse51" class="panel-collapse collapse">';
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse52"><b>Agregar especialidad materia</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse52" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para agregar una <b> Especialidad materia </b>:<br><br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Especialidad_materia</button><br><br>';
				echo '        <b>Paso 2.-</b> Ir al botón   <button type="button" class="btn btn-default"><font color="green"><i class="fa fa-plus-circle fa-1x" aria-hidden="true"> Relación especialidad materia</i></font></button><br><br>';
				echo '        <b>Paso 3.-</b> Llenar el formulario </b><b>RELACIÓN ESPECIALIDAD MATERIA</b><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Guardar</button> (Si es que se desea guardar) ó bien  en el botón   <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desean guardar los datos).<br><br>';
				echo '        Si los datos ingresados fueron correctos, <b>aparecerá el siguiente mensaje:</b><br><br>';
				echo '        <div class="alert alert-success alert-dismissible fade in">';
				echo '            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
				echo '            <center>Relación guardada correctamente</center>';
				echo '        </div>				';
				echo '       <font color="gray">Una vez enviado esté mensaje, se podrán visualizar los datos de la relación especialidad materia en el sistema web.</font></div>';
				echo '      </div>';
				echo '    </div>';
				
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse53"><b>Búsqueda de especialidad materia</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse53" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para la realización de una búsqueda<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Especialidad_materia</button><br><br>';
				echo '        <b>Paso 2.-</b> Posicionar el mouse en la caja de búsqueda <input type="text" placeholder="BUSCAR..."><br><br>';
				echo '        <b>Paso 3.-</b> Posicionar el mouse a mano derecha y seleccionar el tipo de búsqueda'; 
                echo '      <select>';
				echo '      <option value="idespecialidad">Especialidad</option>'; 
				echo '	    <option value="clave_materia">Clave materia</option>';
				echo '		</select>
				(Especialidad, Clave materia)<br><br>';
				echo '        <b>Paso 4.-</b> Introducir el dato a buscar <br><br>Si el dato que se introdujo en la caja de búsqueda es correcto regresara el dato buscado.<br><br>Si el dato que se introdujo en la caja de búsqueda es incorrecto, se mostrará un mensaje de error (De acuerdo al dato de búsqueda).</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse54"><b>Ver especialidad materia</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse54" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para ver la información del Especialidad materia:<br>';
				echo '        <b>Paso 1.-</b>Ir a la pestaña <button class="button button1">Especialidad_materia</button><br><br>';
				echo '        <b>Paso 2.-</b>Dar clic en el icono ver ';
				echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal" style="color:#2A9AFE" data-target="#error_logueo">';
				echo '            <i class="fa fa-search" aria-hidden="true"></i>';
				echo '        </button>';
				echo '   <br><br>Se desplegará una ventana donde se podrán visualizar los datos completos de la especialidad materia.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse55"><b>Editar especialidad</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse55" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para editar una <b> Especialidad materia </b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Especialidad_materia</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Editar (Al deslizar el mouse en  el formulario Especialidad_materia aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Editar</b> ';
				echo            '<i class="fa fa-pencil-square-o fa-1x" aria-hidden="true" style="color:#2E9AFE;"></i><br><br>';			
				echo '        <b>Paso 3.-</b> Aparcerá el formulario </b><b>ACTUALIZAR ESPECIALIDAD MATERIA</b>, modifica el dato que deseas actualizar<br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Actualizar</button> (Si es que se desea actualizar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar </button>(Si es que no se desean guardar los datos).<br><br>';
				echo '        <font color="gray">Si los datos ingresados fueron correctos</font>, aparecerá el siguiente mensaje: <br><br>';
				echo '		  <div class="alert alert-success alert-dismissible">';
				echo '          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
				echo '            <center>Datos editados correctamente</center>';
				echo '        </div>';
				echo '     Una vez enviada la actualización, se podrán visualizar los datos actualizados en el sistema web.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse56"><b>Eliminar especialidad</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse56" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para eliminar una <b>Especialidad materia</b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Especialidad_materia</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Eliminar (Al deslizar el mouse en  el formulario Especialidad_materia aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Eliminar</b>';
				echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal"  style="color:#2E9AFE;" data-target='.'"'."#"."eliminar_materia".$idmateria.'" '.'>';
				echo '           <i class="fa fa-trash-o fa-2x" aria-hidden="true" style="color:#2E9AFE;"></i><br>';
				echo '        </button>';
				echo '        <br><br><b>Paso 3.-</b> Aparcerá el formulario </b><b>ELIMINAR ESPECIALIDAD MATERIA</b> con el siguiente mensaje: <b>¿Está seguro de eliminar la relación (Especialidad-Materia)?</b>,<font color="blue"> Una vez eliminada no se podrá recuperar.</font><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Eliminar</button> (Si es que se desea eliminar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desea eliminar la Especialidad materia).<br><br>';
				echo '        <font color="gray">Si se acepto la eliminación de la especialidad materia</font>, aparecerá el siguiente mensaje:<br><br>';
				echo '        <div class="alert alert-success alert-dismissible">';
				echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
				echo '             <center>Especialidad materia eliminada correctamente<center>';
				echo '        </div>';
				echo '        Una vez eliminada la especialidad materia, no existirá registro de esta relación.</div>';
				echo '      </div>';
				echo '    </div>';
				echo '</div>';
				echo '<br>';
				
				echo '<div class="panel panel-warning">';
                echo '    <div class="panel panel-warning">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse57"><div class="panel-heading">Menú de Ayuda <i class="fa fa-question-circle" aria-hidden="true"></i> (Carrera) <i class="fa fa-book fa-2x" aria-hidden="true"></i>       <center><i class="fa fa-angle-down" aria-hidden="true"> Desglosa aquí</i></center></div></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse57" class="panel-collapse collapse">';
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse58"><b>Agregar carrera</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse58" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para agregar una <b> Carrera </b>:<br><br>';
			    echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Carrera</button><br><br>';
				echo '        <b>Paso 2.-</b> Ir al botón   <button type="button" class="btn btn-default"><font color="green"><i class="fa fa-plus-circle fa-1x" aria-hidden="true"> Agregar Carrera</i></font></button><br><br>';
				echo '        <b>Paso 3.-</b> Llenar el formulario </b><b>NUEVA CARRERA</b><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Guardar</button> (Si es que se desea guardar) ó bien  en el botón   <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desean guardar los datos).<br><br>';
				echo '        Si los datos ingresados fueron correctos, <b>aparecerá el siguiente mensaje:</b><br><br>';
				echo '        <div class="alert alert-success alert-dismissible fade in">';
				echo '            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
				echo '            <center> Carrera guardada correctamente</center>';
				echo '        </div>				';
				echo '       <font color="gray">Una vez enviado esté mensaje, se podrán visualizar los datos de la Carrera agregada en el sistema web.</font></div>';
				echo '      </div>';
				echo '    </div>';
				
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse59"><b>Búsqueda de carrera</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse59" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para la realización de una búsqueda<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Carrera</button><br><br>';
				echo '        <b>Paso 2.-</b> Posicionar el mouse en la caja de búsqueda <input type="text" placeholder="BUSCAR..."><br><br>';
				echo '        <b>Paso 3.-</b> Posicionar el mouse a mano derecha y seleccionar el tipo de búsqueda'; 
                echo '      <select>';
				echo '      <option value="idespecialidad">Especialidad</option>'; 
				echo '	    <option value="clave_materia">Clave materia</option>';
				echo '		</select>
				(Especialidad, Clave materia)<br><br>';
				echo '        <b>Paso 4.-</b> Introducir el dato a buscar <br><br>Si el dato que se introdujo en la caja de búsqueda es correcto regresara el dato buscado.<br><br>Si el dato que se introdujo en la caja de búsqueda es incorrecto, se mostrará un mensaje de error (De acuerdo al dato de búsqueda).</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse60"><b>Ver carrera</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse60" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para ver la información del Carrera:<br>';
				echo '        <b>Paso 1.-</b>Ir a la pestaña <button class="button button1">Carrera</button><br><br>';
				echo '        <b>Paso 2.-</b>Dar clic en el icono ver ';
				echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal" style="color:#2A9AFE" data-target="#error_logueo">';
				echo '            <i class="fa fa-search" aria-hidden="true"></i>';
				echo '        </button>';
				echo '   <br><br>Se desplegará una ventana donde se podrán visualizar los datos completos de la Carrera.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse61"><b>Editar carrera</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse61" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para editar una <b> Carrera </b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Carrera</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Editar (Al deslizar el mouse en  el formulario Carrera aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Editar</b> ';
				echo            '<i class="fa fa-pencil-square-o fa-1x" aria-hidden="true" style="color:#2E9AFE;"></i><br><br>';			
				echo '        <b>Paso 3.-</b> Aparcerá el formulario </b><b>ACTUALIZAR CARRERA</b>, modifica el dato que deseas actualizar<br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Actualizar</button> (Si es que se desea actualizar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar </button>(Si es que no se desean guardar los datos).<br><br>';
				echo '        <font color="gray">Si los datos ingresados fueron correctos</font>, aparecerá el siguiente mensaje: <br><br>';
				echo '		  <div class="alert alert-success alert-dismissible">';
				echo '          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
				echo '            <center>Datos editados correctamente</center>';
				echo '        </div>';
				echo '     Una vez enviada la actualización, se podrán visualizar los datos actualizados en el sistema web.</div>';
				echo '      </div>';
				echo '    </div>';
				
				echo '    <div class="panel panel-default">';
				echo '      <div class="panel-heading">';
				echo '        <h4 class="panel-title">';
				echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse62"><b>Eliminar carrera</b></a>';
				echo '        </h4>';
				echo '      </div>';
				echo '      <div id="collapse62" class="panel-collapse collapse">';
				echo '        <div class="panel-body">Pasos para eliminar una <b>Carrera</b>:<br>';
				echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Carrera</button><br><br>';
				echo '        Posiciona el mouse en la fila que se desea Eliminar (Al deslizar el mouse en  el formulario Carrera aparecerá un selector color gris)<br><br>';
				echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Eliminar</b>';
				echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal"  style="color:#2E9AFE;" data-target='.'"'."#"."eliminar_carrera".$idcarrera.'" '.'>';
				echo '           <i class="fa fa-trash-o fa-2x" aria-hidden="true" style="color:#2E9AFE;"></i><br>';
				echo '        </button>';
				echo '        <br><br><b>Paso 3.-</b> Aparcerá el formulario </b><b>ELIMINAR CARRERA</b> con el siguiente mensaje: <b>¿Está seguro de eliminar esta Carrera?</b>,<font color="blue"> Una vez eliminada no se podrá recuperar.</font><br><br>';
				echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Eliminar</button> (Si es que se desea eliminar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desea eliminar la Carrera).<br><br>';
				echo '        <font color="gray">Si se acepto la eliminación del Carrera</font>, aparecerá el siguiente mensaje:<br><br>';
				echo '        <div class="alert alert-success alert-dismissible">';
				echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
				echo '             <center>Carrera eliminada correctamente<center>';
				echo '        </div>';
				echo '        Una vez eliminada la carrera, no existirá registro de ella.</div>';
				echo '      </div>';
				echo '    </div>';
				echo '  </div>'; 
				echo '<br>';
						
				echo '  </div> ';
				echo '</div>';					
          		?>
            </div>  	
      </div>
    <script src="../js/jquery.js"></script>
    <script src="../js/bootstrap.js"></script>
  </body>
</html>