<?php
echo ' <div class="container">';
					echo '  <h2>Menú de Ayuda</h2>';
					echo '  <p><strong>Nota:</strong> Dé un <strong>clic</strong> sobre la consulta que desea visualizar (Al dar clic se desplegará el formulario de ayuda buscado).</p>';
					echo '  <div class="panel-group" id="accordion">';
					
					echo '    <div class="panel panel-default">';
					echo '      <div class="panel-heading">';
					echo '        <h4 class="panel-title">';
					echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse1"><b>Agregar usuario</b></a>';
					echo '        </h4>';
					echo '      </div>';
					echo '      <div id="collapse1" class="panel-collapse collapse in">';
					echo '        <div class="panel-body">Pasos para agregar un <b> Usuario </b>:<br><br>';
					echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Usuarios</button><br><br>';
					echo '        <b>Paso 2.-</b> Ir al botón   <button type="button" class="btn btn-default"><font color="green"><i class="fa fa-plus-circle fa-1x" aria-hidden="true"> Agregar Usuario</i></font></button><br><br>';
					echo '        <b>Paso 3.-</b> Llenar el formulario </b><b>NUEVO USUARIO</b><br><br>';
					echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Guardar</button> (Si es que se desea guardar) ó bien  en el botón   <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desean guardar los datos).<br><br>';
					echo '        Si los datos ingresados fueron correctos, <b>aparecerá el siguiente mensaje:</b><br><br>';
					echo '        <div class="alert alert-success alert-dismissible fade in">';
					echo '            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
					echo '            <center> Usuario guardado correctamente</center>';
					echo '        </div>				';
					echo '  <font color="gray">Una vez enviado esté mensaje, se podrán visualizar los datos del usuario agregado en el sistema web.</font></div>';				
					echo '      </div>';
					echo '    </div>';
					
					echo '    <div class="panel panel-default">';
					echo '      <div class="panel-heading">';
					echo '        <h4 class="panel-title">';
					echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse2"><b>Importar una lista de usuarios</b></a>';
					echo '        </h4>';
					echo '      </div>';
					echo '      <div id="collapse2" class="panel-collapse collapse">';
					echo '        <div class="panel-body">Si usted tiene una larga lista de usuarios y no los quiere llenar manualmente en el sistema (le tenemos una solución, Importar una lista de usuarios en excel)<br><br>';
					echo '        Pasos para importar una <b> Lista de Usuarios </b>:<br>';
					echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Usuarios</button><br><br>';	
					echo '        <b>Paso 2.-</b> Dar clic en el botón <div class="well"><center><font color="blue">¿Deseas importar una lista de usuarios?, Da clic aquí</font></center></div>';
					echo '        <b><font color="grey">Una vez que haya dado clic se desplazara un ventana informativa</font></b>, en donde se podrá <b><font color="green"><i class="fa fa-download" aria-hidden="true"> </i></font><font color="blue"> Descargar plantilla </font></b><b>(responsable.csv)</b><br><br></font>';
					echo '        <b>Paso 3.-</b> Abrir la plantilla <b>responsable.csv</b> y llenarla con los datos requeridos en la parte superior del archivo (En la parte izquierda viene un ejemplo)<br><br></b>';
					echo '        Una vez que todos los capos hayan sido llenados se le da guardar al archivo <b>(responsable.csv)</b> y nos regresamos al formulario del usuario <br><br></b>';
					echo '        <b>Paso 4.-</b> Seleccionamos el botón <b>Seleccionar archivo</b>, El cual desplegará una ventana de búsqueda, seleccionamos el archivo <b>(responsable.csv)</b><br><br>';
					echo '        <b>Paso 5.-</b> Damos clic en abrir (Una vez hecho estó se cargara el nombre del archivo )<br><br>';
					echo '        <b>Paso 6.-</b> Dar clic en el botón <button type="button"><font color="green">Cargar</font></button><br><br>';
					echo '        Si los datos ingresados fueron correctos, <b>aparecerá el siguiente mensaje:</b> <br><br>';
					echo '       <div class="alert alert-success alert-dismissible fade in">';
					echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
					echo '             <center>Archivo importado correctamente</center>';
					echo '       </div>';
					echo '  <font color="gray">Una vez enviado esté mensaje, se podrán visualizar los datos del usuario agregado en el sistema web.</font><br><br>';
					echo '       Si el archivo importado es incorrecto, <b>aparecerá el siguiente mensaje:</b><br><br>';
					echo '       <div class="alert alert-danger alert-dismissible fade in">';
					echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
					echo '           <center>¡Archivo inválido!, No se cargaron los datos </center>';
					echo '       </div>';
					echo 'ó bien si el archivo tiene datos dúplicados, <b>aparecerá esté otro mensaje:</b><br><br>';
					echo '       <div class="alert alert-danger alert-dismissible fade in">';
					echo '          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
					echo '          <center>¡Archivo inválido! No cumple con el formato indicado ó hay datos dúplicados (los datos no dúplicados si se guardaran)</center>';
					echo '       </div>';
					echo '      </div>';
					echo '      </div>';
					echo '    </div>';
					
					echo '    <div class="panel panel-default">';
					echo '      <div class="panel-heading">';
					echo '        <h4 class="panel-title">';
					echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse3"><b>Búsqueda de usuarios</b></a>';
					echo '        </h4>';
					echo '      </div>';
					echo '      <div id="collapse3" class="panel-collapse collapse">';
					echo '        <div class="panel-body">Pasos para la realización de una búsqueda ';
					echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Usuarios</button><br><br><br>';
					echo '        <b>Paso 2.-</b> Posicionar el mouse en la caja de búsqueda <input type="text" placeholder="BUSCAR..."><br><br>';
					echo '        <b>Paso 3.-</b> Posicionar el mouse a mano derecha y seleccionar el tipo de búsqueda'; 
					echo '      <select>';
					echo '			  <option value="usuario">Usuario</option>';
					echo '			  <option value="nombre>Nombre</option>';
					echo '			  <option value="ap">Apellido Paterno</option>';
					echo '			  <option value="am">Apellido Materno</option>';
					echo '			  <option value="puesto">Puesto</option>';
					echo '			</select>
					(Usuario, Nombre, Apellido Paterno, Apellido Materno, Puesto)<br><br>';
					echo '        <b>Paso 4.-</b> Introducir el dato a buscar <br><br>Si el dato que se introdujo en la caja de búsqueda es correcto regresara el dato buscado.<br><br>Si el dato que se introdujo en la caja de búsqueda es incorrecto, se mostrará un mensaje de error (De acuerdo al dato de búsqueda).</div>';
					echo '      </div>';
					echo '    </div>';
					
					echo '    <div class="panel panel-default">';
					echo '      <div class="panel-heading">';
					echo '        <h4 class="panel-title">';
					echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse4"><b>Ver usuarios</b></a>';
					echo '        </h4>';
					echo '      </div>';
					echo '      <div id="collapse4" class="panel-collapse collapse">';
					echo '        <div class="panel-body">Pasos para ver usuarios:<br>';
					echo '        <b>Paso 1.-</b>Ir a la pestaña <button class="button button1">Usuarios</button><br><br>';
					echo '        <b>Paso 2.-</b>Dar clic en el icono ver ';
					echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal" style="color:#2A9AFE" data-target="#error_logueo">';
					echo '            <i class="fa fa-search" aria-hidden="true"></i>';
					echo '        </button>';
					echo '   <br><br>Se desplegará una ventana donde se podrán visualizar los datos completos del usuario.</div>';
					echo '      </div>';
					echo '    </div>';
					
					echo '    <div class="panel panel-default">';
					echo '      <div class="panel-heading">';
					echo '        <h4 class="panel-title">';
					echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse5"><b>Editar usuario</b></a>';
					echo '        </h4>';
					echo '      </div>';
					echo '      <div id="collapse5" class="panel-collapse collapse">';
					echo '        <div class="panel-body">Pasos para editar un <b> Usuario </b>:<br>';
					echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Usuarios</button><br><br>';
					echo '        Posiciona el mouse en la fila que se desea Editar (Al deslizar el mouse en  el formulario usuarios aparecerá un selector color gris)<br><br>';
					echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Editar</b> ';
					echo            '<i class="fa fa-pencil-square-o fa-1x" aria-hidden="true" style="color:#2E9AFE;"></i><br><br>';			
					echo '        <b>Paso 3.-</b> Aparcerá el formulario </b><b>ACTUALIZAR USUARIO</b>, modifica el dato que deseas actualizar<br><br>';
					echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Actualizar</button> (Si es que se desea actualizar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar </button>(Si es que no se desean guardar los datos).<br><br>';
					echo '        <font color="gray">Si los datos ingresados fueron correctos</font>, aparecerá el siguiente mensaje: <br><br>';
					echo '		  <div class="alert alert-success alert-dismissible">';
					echo '          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
					echo '            <center>Datos editados correctamente</center>';
					echo '        </div>';
					echo '     Una vez enviada la actualización, se podrán visualizar los datos actualizados en el sistema web.</div>';
					echo '      </div>';
					echo '    </div>';
					
					echo '    <div class="panel panel-default">';
					echo '      <div class="panel-heading">';
					echo '        <h4 class="panel-title">';
					echo '          <a data-toggle="collapse" data-parent="#accordion" href="#collapse6"><b>Eliminar usuario</b></a>';
					echo '        </h4>';
					echo '      </div>';
					echo '      <div id="collapse6" class="panel-collapse collapse">';
					echo '        <div class="panel-body">Pasos para editar un <b> Usuario </b>:<br>';
					echo '        <b>Paso 1.-</b> Ir a la pestaña <button class="button button1">Usuarios</button><br><br>';
					echo '        Posiciona el mouse en la fila que se desea Eliminar (Al deslizar el mouse en  el formulario usuarios aparecerá un selector color gris)<br><br>';
					echo '        <b>Paso 2.-</b> Dar clic en el icono <b>Eliminar</b>';
					echo '        <button type="button" class="btn btn-default btn-xs" data-toggle="modal"  style="color:#2E9AFE;" data-target='.'"'."#"."eliminar_usuario".$idusuario.'" '.'>';
					echo '           <i class="fa fa-trash-o fa-2x" aria-hidden="true" style="color:#2E9AFE;"></i><br>';
					echo '        </button>';
					echo '        <br><br><b>Paso 3.-</b> Aparcerá el formulario </b><b>ELIMINAR USUARIO</b> con el siguiente mensaje: <b>¿Está seguro de eliminar este usuario?</b>,<font colo="blue"> Una vez eliminado no se podrá recuperar.</font><br><br>';
					echo '        <b>Paso 4.-</b> Dar clic en el botón <button type="button" class="btn btn-success">Eliminar</button> (Si es que se desea eliminar) ó bien  en el botón <button type="button" class="btn btn-default">Cancelar</button> (Si es que no se desea eliminar el usuario).<br><br>';
					echo '        <font color="gray">Si se acepto la eliminación del usuario</font>, aparecerá el siguiente mensaje:<br><br>';
					echo '        <div class="alert alert-success alert-dismissible">';
					echo '           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>';
					echo '             <center>Usuario eliminado correctamente<center>';
					echo '        </div>';
					echo '        Una vez eliminado el usuario, no existirá registro de él.</div>';
					echo '      </div>';
					echo '    </div>';
					
					echo '  </div> ';
					echo '</div>';
					?>